site_name: Try Pages
site_url: https://dmitry-borodkin.github.io/try-pages

theme:
  name: material
  palette:
    primary: white

markdown_extensions:
  - pymdownx.tilde
  - pymdownx.emoji

nav:
  - Welcome to MkDocs: index.md
  - Strange: strange.md
  - Tutorial: tutorial.md

